Feature/tasks
Spola1/TaskManager pull request #15
Opened 2022-09-28 11:17 UTC by Spola1

2022-09-29 16:48 UTC, greybutton requested changes

2022-09-29 16:48 UTC, greybutton commented on Gemfile
> +gem 'react-rails', '~> 1.0'
зачем этот гем?

2022-09-29 16:48 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    render(json: tasks, each_serializer: TaskSerializer, root: 'items', meta: build_meta(tasks))
почему поменял respond_with на render?

2022-09-29 16:48 UTC, greybutton commented on app/javascript/components/AddPopup/AddPopup.js
> +function AddPopup({ onClose, onCreateCard }) {
почему такой синтаксис?

2022-09-29 16:48 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +import CloseIcon from '@material-ui/icons/Close';
хорошо бы импорты пакетов не смешивать с локальными импортами

2022-09-29 16:48 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    tasks = Task.order(id: :desc).
добавили же сортировку через рансак, зачем такую хардкодить?

2022-09-29 16:48 UTC, greybutton commented on package.json
> +    "react-is": "^16.8.0",
не используемый пакет

2022-09-29 16:48 UTC, greybutton commented on package.json
> +    "@lourenci/react-kanban": "^2.1.0",
этот пакет можно удалить, в теории случайно остался

2022-09-30 06:02 UTC, Spola1 commented on app/controllers/api/v1/tasks_controller.rb
> +    render(json: tasks, each_serializer: TaskSerializer, root: 'items', meta: build_meta(tasks))
потому что при переходе на api/v1/tasks 
вы летала ошибка ActionController::UnknownFormat in Api::V1::TasksController#index
с подсвечиванием этой строки, соответственно на главной не отображались и не создавались новые карточки

2022-09-30 06:10 UTC, Spola1 commented on Gemfile
> +gem 'react-rails', '~> 1.0'
без этого гема у  меня undefined method `react_component' for #<ActionView::Base:0x0000000000a460>
во вьюхе /views/web/boards/show.html.slim

2022-09-30 06:10 UTC, Spola1 commented on Gemfile
> +gem 'react-rails', '~> 1.0'
без этого гема у  меня undefined method `react_component' for #<ActionView::Base:0x0000000000a460>
во вьюхе /views/web/boards/show.html.slim

2022-09-30 06:24 UTC, Spola1 commented on app/controllers/api/v1/tasks_controller.rb
> +    render(json: tasks, each_serializer: TaskSerializer, root: 'items', meta: build_meta(tasks))
та же история, кстати, с экшеном show 
нажимая на редактирование карточки с respond with просто идет бесконечная загрузка, а в консоли 

ActionController::UnknownFormat (ActionController::UnknownFormat):

app/controllers/api/v1/tasks_controller.rb:15:in `show'

2022-09-30 06:26 UTC, Spola1 commented on app/javascript/components/AddPopup/AddPopup.js
> +function AddPopup({ onClose, onCreateCard }) {
что-то у меня не получалось(не помню конкретно что)
то-ли кнопка(плюсик не реагировала), то-ли еще что-то
пробовал разные варианты фикса 
сейчас работает и с вашим вариантом, вернул обратно

2022-09-30 06:29 UTC, Spola1 commented on app/javascript/components/EditPopup/EditPopup.js
> +import CloseIcon from '@material-ui/icons/Close';
исправил

2022-09-30 06:40 UTC, Spola1 commented on app/controllers/api/v1/tasks_controller.rb
> +    tasks = Task.order(id: :desc).
для надежности
ну или по-глупости
на ваш выбор 

убрал сортировку из контроллера

2022-09-30 06:56 UTC, Spola1 commented on package.json
> +    "@lourenci/react-kanban": "^2.1.0",
удалил

2022-09-30 08:12 UTC, greybutton commented on Gemfile
> +gem 'react-rails', '~> 1.0'
попробуй поставить webpacker-react

2022-09-30 08:13 UTC, Spola1 commented on package.json
> +    "react-is": "^16.8.0",
возможно и неиспользуемый, но при сборке без него вылетает неприятный красный
warning " > styled-components@5.3.6" has unmet peer dependency "react-is@>= 16.8.0".
но в принципе без него тоже работает. удалил

2022-09-30 08:14 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    render(json: tasks, each_serializer: TaskSerializer, root: 'items', meta: build_meta(tasks))
перепроверь предыдущие уроки, может что то пропустили. respond_with должен работать

2022-09-30 08:34 UTC, Spola1 commented on Gemfile
> +gem 'react-rails', '~> 1.0'
в package.json у меня есть "webpacker-react": "^0.3.2"
поставил еще гем webpacker-react

Ошибка при запуске сервера(всё предварительно сбилжено): 
web_1  | bundler: failed to load command: rails (/bundle_cache/ruby/2.7.0/bin/rails)
web_1  | Bundler::GemNotFound: Could not find webpacker-react-0.3.2 in any of the sources

Оставил пока что gem 'react-rails', '~> 1.0'

2022-09-30 18:16 UTC, greybutton commented on Gemfile
> +gem 'react-rails', '~> 1.0'
может быть `bundle install` забыли запустить после добавления в Gemfile? мне кажется должно работать с `gem 'webpacker-react', '0.3.2'`

вы молодец, что нашли решение. Я хочу убедиться, что гем webpacker-react точно не работает, возможно нам нужно будет обновить теорию. Вы пока первый кто с этим столкнулся из группы и вы ушли далеко вперед группы, поэтому я бы хотел вас попросить сделать ресерч

2022-10-03 16:19 UTC, greybutton commented on Gemfile
> +gem 'react-rails', '~> 1.0'
у другого студента получилось с webpacker-react

2022-10-03 16:21 UTC, greybutton approved these changes

2022-10-03 16:21 UTC, greybutton commented on app/views/web/boards/show.html.slim
> += react_component('TaskBoard')
можно вернуть в контроллер

2022-10-03 18:27 UTC, merged