Feature/GitHub actions
Spola1/TaskManager pull request #18
Opened 2022-10-17 07:41 UTC by Spola1

2022-10-17 17:37 UTC, greybutton requested changes

2022-10-17 17:37 UTC, greybutton commented on test/controllers/api/v1/tasks_controller_test.rb
> +    created_task.expired_at = (Time.now + 1.hour).to_date
это заглушка для тестов, а в приложении недоработка осталась

2022-10-28 10:42 UTC, Spola1 commented on test/controllers/api/v1/tasks_controller_test.rb
> +    created_task.expired_at = (Time.now + 1.hour).to_date
исправил

2022-10-28 17:55 UTC, greybutton approved these changes

2022-10-31 07:37 UTC, merged