add simplecov
Spola1/TaskManager pull request #20
Opened 2022-11-02 11:32 UTC by Spola1

2022-11-02 15:15 UTC, greybutton requested changes

2022-11-02 15:15 UTC, greybutton commented on Gemfile
> +gem 'dotenv'
зачем этот гем?

2022-11-02 15:15 UTC, greybutton commented on test/test_helper.rb
> +
покрытие лучше генерировать только если тесты через CI запущены, иначе всегда будут генерироваться на запуск тестов, а всегда не нужно. С таким кодом не уверен, что так работает

2022-11-03 08:45 UTC, Spola1 commented on Gemfile
> +gem 'dotenv'
в принципе для хранения env ключей в файлике .env

не понял изначально куда ключ прописывать поэтому добавил этот гем

уже разобрался, убрал гем

2022-11-03 08:46 UTC, Spola1 commented on test/test_helper.rb
> +
вроде поправил

2022-11-03 17:46 UTC, greybutton approved these changes

2022-11-04 07:34 UTC, merged